### DISCUSSION TITLE
Running gramps-web via docker with traefik as reverse proxy

### DISCUSSION THREAD

**Discussion by Buddinski88** [gramps-project/gramps-web#279] [Q&A] [answered]
Hello all,

I would like to use gramps-web using Traefik as a reverse proxy, as I use it to use all my other services. Unfortunately, I am having difficulties with this. So I was wondering if there is an example of how someone else has implemented it using Traefik instead of nginx-proxy?

Thanks a lot and greetings,
Bastian

**Comment by DavidMStraub** [comment]
I am not aware of an example (which doesn't mean none exists).

**Reply by Buddinski88** [reply]
Maybe someone else is my question reading as well.

With the following `docker-compose.yml` i get a 502 http error.

```yaml
version: "3.7"

services:
  grampsweb: &grampsweb
    image: ghcr.io/gramps-project/grampsweb:latest
    restart: always
    ports:
      - "8200:5000"  # host:docker
    environment:
      GRAMPSWEB_TREE: "Gramps Web"  # will create a new tree if not exists
      GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_RATELIMIT_STORAGE_URI: redis://grampsweb_redis:6379/1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grampsweb.entrypoints=http"
      - "traefik.http.routers.grampsweb.rule=Host(`***.de`)"
      - "traefik.http.middlewares.grampsweb-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.grampsweb.middlewares=grampsweb-https-redirect"
      - "traefik.http.routers.grampsweb-secure.entrypoints=https"
      - "traefik.http.routers.grampsweb-secure.rule=Host(`***.de`)"
      - "traefik.http.routers.grampsweb-secure.tls=true"
      - "traefik.http.routers.grampsweb-secure.service=grampsweb"
      - "traefik.http.services.grampsweb.loadbalancer.server.port=8200"
      - "traefik.docker.network=traefik_proxy"
      #- "com.centurylinklabs.watchtower.monitor-only=true"
    depends_on:
      - grampsweb_redis
    volumes:
      - gramps_users:/app/users  # persist user database
      - gramps_index:/app/indexdir  # persist search index
      - gramps_thumb_cache:/app/thumbnail_cache  # persist thumbnails
      - gramps_cache:/app/cache  # persist export and report caches
      - gramps_secret:/app/secret  # persist flask secret
      - gramps_db:/root/.gramps/grampsdb  # persist Gramps database
      - gramps_media:/app/media  # persist media files
      - gramps_tmp:/tmp
    networks:
      - traefik_proxy

  grampsweb_celery:
    <<: *grampsweb  # YAML merge key copying the entire grampsweb service config
    ports: []
    container_name: grampsweb_celery
    depends_on:
      - grampsweb_redis
    command: celery -A gramps_webapi.celery worker --loglevel=INFO
    networks:
      - traefik_proxy

  grampsweb_redis:
    image: redis:alpine
    container_name: grampsweb_redis
    restart: always
    networks:
      - traefik_proxy

volumes:
  gramps_users:
  gramps_index:
  gramps_thumb_cache:
  gramps_cache:
  gramps_secret:
  gramps_db:
  gramps_media:
    driver: local
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=10.10.10.40,rw"
      device: ":/volume1/docker-volumes/gramps-web"
  gramps_tmp:

networks:
  traefik_proxy:
    external: true
```

Via internal ip it's accessible.

**Comment by mpfl** [comment, marked as answer]
This is my config. I've already set up an entrypoint to get a wildcard SSL cert. I also use a middleware that sets some HTTP headers to enhance security. My `web` network is analogous to your `traefik_proxy` network.

```yaml
version: "3.7"

services:
  grampsweb: &grampsweb
    image: ghcr.io/gramps-project/grampsweb:latest
    container_name: grampsweb
    networks:
      - default
      - web
    environment:
      GRAMPSWEB_TREE: "My family"  # will create a new tree if not exists
      GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://grampsweb-redis:6379/0"
      GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://grampsweb-redis:6379/0"
      GRAMPSWEB_RATELIMIT_STORAGE_URI: "redis://grampsweb-redis:6379/1"
    depends_on:
      - grampsweb-redis
    volumes:
      - /home/gramps/app/users:/app/users  # persist user database
      - /home/gramps/app/indexdir:/app/indexdir  # persist search index
      - /home/gramps/app/thumbnail_cache:/app/thumbnail_cache  # persist thumbnails
      - /home/gramps/app/cache:/app/cache  # persist export and report caches
      - /home/gramps/app/secret:/app/secret  # persist flask secret
      - /home/gramps/app/grampsdb:/root/.gramps/grampsdb  # persist Gramps database
      - /home/gramps/app/media:/app/media  # persist media files
      - /home/gramps/app/tmp:/tmp
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.gramps.entrypoints=websecure"
      - "traefik.http.routers.gramps.rule=Host(`gramps.my.domain`)"
      - "traefik.http.services.gramps.loadbalancer.server.port=5000"
      - "traefik.http.routers.gramps.middlewares=security@docker"
    restart: unless-stopped

  grampsweb-celery:
    <<: *grampsweb  # YAML merge key copying the entire grampsweb service config
    ports: []
    container_name: grampsweb-celery
    depends_on:
      - grampsweb-redis
    command: celery -A gramps_webapi.celery worker --loglevel=INFO
    labels: []

  grampsweb-redis:
    image: redis:alpine
    container_name: grampsweb-redis
    restart: unless-stopped 

networks:
  web:
    external: true
```
