### DISCUSSION TITLE
Why so many volumes?

### DISCUSSION THREAD

**Discussion by pwalkr** [gramps-project/gramps-web#478] [Q&A]
Hello! Gramps is a fantastic application. I have been self-hosting an HTML export of my tree for years and I'm excited to see an official hosted solution with docker. Thank you!

Is it safe/possible to use fewer volume mounts? Per [docker-compose.yml](https://raw.githubusercontent.com/gramps-project/gramps-web-docs/cf4c923/examples/docker-compose-base/docker-compose.yml) there's 8 volumes, 6 of which are subdirectories of `/app`.

Would it be bad to simply mount a `gramps_data` on `/app`?

Is mounting `/tmp` necessary?

I'd love for a single volume to backup/restore, relocate as needed. If `/app` doesn't contain anything that *should* be discarded on restart, `/tmp` isn't necessary, and `grampsdb` is relocatable based on ENV then it would be possible.

\*I see `/tmp` was added to [share with celery](https://github.com/gramps-project/gramps-web-docs/commit/6d48d20d16e2cbfc027779330f6c02095275266c) - I've no experience with celery, but it seems like redis should be the only necessary link between containers. Is that resolvable?

**Comment by DavidMStraub** [comment]
Hi! Thanks for the nice words.

You can use less volumes if you like - the main reason for splitting them was actually that not all of them are equally relevant for a backup.

> Would it be bad to simply mount a gramps_data on /app?

Yep, that would be bad, because `/app` contains the source code for Web API: https://github.com/gramps-project/gramps-web-api/blob/master/Dockerfile#L67

> Is mounting /tmp necessary?

It's necessary, yes, because that's how the Web API container and the Celery container share temporary files (e.g., the celery container creates an export and the flask container serves it). Using redis for that doesn't make sense - imagine generating a media archive ZIP, which can be GB in size.

> I'd love for a single volume to backup/restore, relocate as needed. If /app doesn't contain anything that should be discarded on restart, /tmp isn't necessary, and grampsdb is relocatable based on ENV then it would be possible.

It's still possible. Nothing stops you from changing the config as well, see https://www.grampsweb.org/Configuration/. Then you can move media, search index, and Gramps database into the same folder. However it might require you to create some subdirectories which are not present in the image yet, so not 100% sure it's possible without creating your own image or modifying the entrypoint.

If you want to move the Gramps database away from `/root/.gramps/grampsdb`, you can probably do so by setting the [`GRAMPSHOME` env variable](https://www.gramps-project.org/wiki/index.php/Gramps_5.1_Wiki_Manual_-_Command_Line#GRAMPSHOME).

**Comment by pwalkr** [comment]
Ah, there is a lot in `/app` besides the user-specific data. Thank you for clarifying. I will look at relocating the folders so they can be kept together without clobbering everything else. Maybe just a subvolume type mount.

Have you considered moving [gunicorn](https://github.com/gramps-project/gramps-web-api/blob/9bbd09708d03936513beaefeb05e1ed2e265de77/Dockerfile#L75) and [celery](https://github.com/gramps-project/gramps-web-docs/blob/d73f23eb4b3bf3465dbad65ff647460450e3f8e7/examples/docker-compose-base/docker-compose.yml#L32) into the same container with init/tini? It would eliminate the tmp volume, but it may be useful to keep them separate for scaling.

**Comment by DavidMStraub** [comment]
> Have you considered moving [gunicorn](https://github.com/gramps-project/gramps-web-api/blob/9bbd09708d03936513beaefeb05e1ed2e265de77/Dockerfile#L75) and [celery](https://github.com/gramps-project/gramps-web-docs/blob/d73f23eb4b3bf3465dbad65ff647460450e3f8e7/examples/docker-compose-base/docker-compose.yml#L32) into the same container with init/tini? It would eliminate the tmp volume, but it may be useful to keep them separate for scaling.

I haven't, and think it's cleaner to keep them separate.

**Comment by pwalkr** [comment]
After https://github.com/gramps-project/gramps-web-api/pull/538, my [docker-compose.yml](https://github.com/gramps-project/gramps-web-docs/blob/78bf26329d849bb7fcca88e0162f9f379b3ca969/examples/docker-compose-base/docker-compose.yml) is down to two mounts, and the whole instance seems to have survived simply `mv`ing the folders into a single `/data` dir with the associated env being set (existing instance. I have not tried on a net-new install). Copied below to have all the path keys in one place.

Not included: `/app/cache` - I believe this would be relocated via `GRAMPSWEB_REPORT_DIR` and/or `GRAMPSWEB_EXPORT_DIR` ([gramps-web-api/gramps_webapi/config.py](https://github.com/gramps-project/gramps-web-api/blob/9bbd09708d03936513beaefeb05e1ed2e265de77/gramps_webapi/config.py#L56)). But I plan to run this remotely and Gramps Web Sync to local for development and any reporting so I don't think I need it. Please correct me if wrong.

Bonus: this works as non-root. After `chown -R 1000:100 data/` it started back up with `user: '1000'` (again, likely to have issues on a net-new installation)

```
version: "3.7"

services:
  grampsweb: &grampsweb
    image: grampsweb-no-app-secret  # Locally built, uses https://github.com/gramps-project/gramps-web-api/pull/538
    user: '1000'
    restart: always
    ports:
      - "80:5000"  # host:docker
    environment:
      GRAMPSWEB_TREE: "Gramps Web"  # will create a new tree if not exists
      GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_RATELIMIT_STORAGE_URI: redis://grampsweb_redis:6379/1
      GRAMPSHOME: /data
      GRAMPSWEB_SEARCH_INDEX_DB_URI: sqlite:////data/search_index.db
      GRAMPSWEB_MEDIA_BASE_DIR: /data/media
      GRAMPSWEB_USER_DB_URI: sqlite:////data/users.sqlite
      GRAMPSWEB_SECRET_KEY: '*****************'
      GRAMPSWEB_THUMBNAIL_CACHE_CONFIG__CACHE_DIR: /data/thumbnail_cache
    depends_on:
      - grampsweb_redis
    volumes:
      - /home/user/grampsweb/data:/data
      - /home/user/grampsweb/tmp:/tmp

  grampsweb_celery:
    <<: *grampsweb  # YAML merge key copying the entire grampsweb service config
    ports: []
    container_name: grampsweb_celery
    depends_on:
      - grampsweb_redis
    command: celery -A gramps_webapi.celery worker --loglevel=INFO

  grampsweb_redis:
    image: docker.io/library/redis:7.2.4-alpine
    container_name: grampsweb_redis
    restart: always
```
