### ISSUE TITLE
Database not Found | family tree 'unnamed tree' not found in database

### ISSUE THREAD

**Issue by PaulJ00** [gramps-project/gramps-web#668]
Hello,

Today i tried to export my Gramps Tree and did end up with the following Error:

![Image](https://github.com/user-attachments/assets/8ffbe3f8-772e-4b4a-84c4-79043872d09e)

I am a bit suprised that gramps cant find my Database but at the same time everything works fine in gramps web. 
Just functions like Export and the repair function did resolve in errors.

After that i did look into the Error Logs:
```

grampsweb_celery  | ValueError: Database path '6c3ee54e-b9eb-44b8-9172-db600dd33ad8'for family tree 'unnamed tree' not found in database directory /root/.gramps/grampsdb
grampsweb_celery  | [2025-05-31 08:54:40,174: INFO/MainProcess] Task gramps_webapi.api.tasks.export_db[5ce4be24-1276-4814-9575-8a5ca8ea9a55] received
grampsweb         | ERROR:root:Error parsing list of recent DBs from file /root/gramps/recent-files-gramps.xml: no element found: line 1, column 0.
grampsweb         | This might indicate a damage to your files.
grampsweb         | If you're sure there is no problem with other files, delete it, and restart Gramps.
grampsweb         | ERROR:root:Error parsing list of recent DBs from file /root/gramps/recent-files-gramps.xml: no element found: line 1, column 0.
grampsweb         | This might indicate a damage to your files.
```
the recent-files-gramps.xml file:
```
<?xml version="1.0" encoding="utf-8"?>
<RecentFiles>
  <RecentItem>
    <Path><![CDATA[/root/.gramps/grampsdb/6c3ee54e-b9eb-44b8-9172-db600dd33ad8]]></Path>
    <Name><![CDATA[Gramps Web]]></Name>
    <Timestamp>1748691454</Timestamp>
  </RecentItem>
</RecentFiles>
```

In the Gramps-Web-DB Volume my Database is still shown (/var/lib/docker/volumes/gramps-web_gramps_db/_data/XXX:

![Image](https://github.com/user-attachments/assets/5cd8b934-cec7-4f13-b102-edd596c6eb8b)

But if i execute the follwing command there is no Database found:

![Image](https://github.com/user-attachments/assets/81eba3d2-f3bd-4baa-b507-70d64c4884c1)

I cant find any Database if i execute "docker compose exec grampsweb ls /root/gramps/grampsdb"

![Image](https://github.com/user-attachments/assets/ea9e89c3-f771-4d01-9acf-4ac67bb31c20)

Here my Compose File:

```
services:
  grampsweb: &grampsweb
    container_name: grampsweb
    image: ghcr.io/gramps-project/grampsweb:latest
    restart: always
    ports:
      - "0.0.0.0:8080:80"
    environment: &grampsweb-env
      GRAMPSWEB_TREE: "Gramps Web"  # will create a new tree if not exists
      GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_RATELIMIT_STORAGE_URI: redis://grampsweb_redis:6379/1
      GRAMPSWEB_IGNORE_DB_LOCK: true
    volumes:
      - gramps_users:/app/users
      - gramps_index:/app/indexdir
      - gramps_thumb_cache:/app/thumbnail_cache
      - gramps_cache:/app/cache
      - gramps_secret:/app/secret
      - gramps_db:/root/.gramps/grampsdb
      - gramps_media:/app/media
      - gramps_tmp:/tmp
    networks:
      - proxy-paul
      - gramps

  grampsweb_celery:
      image: ghcr.io/gramps-project/grampsweb:latest
      restart: always
      container_name: grampsweb_celery
      environment:
        GRAMPSWEB_TREE: "Gramps Web"  # will create a new tree if not exists
        GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://grampsweb_redis:6379/0"
        GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://grampsweb_redis:6379/0"
        GRAMPSWEB_RATELIMIT_STORAGE_URI: redis://grampsweb_redis:6379/1
        GRAMPSWEB_IGNORE_DB_LOCK: true
      depends_on:
        - grampsweb_redis
      networks:
        - proxy-paul
        - gramps
      command: celery -A gramps_webapi.celery worker --loglevel=INFO


  grampsweb_redis:
    image: docker.io/library/redis:7.2.4-alpine
    container_name: grampsweb_redis
    restart: always
    networks:
      - gramps


volumes:
  gramps_users:
  gramps_index:
  gramps_thumb_cache:
  gramps_cache:
  gramps_secret:
  gramps_db:
  gramps_media:
  gramps_tmp:

networks:
  gramps:
  proxy-paul:
    external: true
```

I did use the Gramps Web Sync Addon in the past but im not sure if this created this error.

I am very thankfull for everyone who can help.

Thanks,
Paul

Gramps specs:
Gramps 6.0.1
Gramps Web API 3.1.0
Gramps Web Frontend 25.5.2
Gramps QL 0.4.0
Sifts 1.0.0
locale: en
multi-tree: false
task queue: true
OCR: true
chat: false
